<a href="https://colab.research.google.com/github/pgs2285/BigData_Analysis_License/blob/master/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D%EA%B8%B0%EC%82%AC_%EC%8B%A4%EA%B8%B0_2%EC%9C%A0%ED%98%95_%EC%A4%80%EB%B9%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2 유형 / 데이터 분석

------  
분석문제는 다음과 같은 순서를 따르자.
1. 필요 패키지 임포트  
2. 데이터 불러오기  
3. 데이터 살펴보기
4. 데이터 전처리
5. 분석 데이터셋 준비
6. 데이터 분석 수행
7. 성능평가 및 시각화
------  
아래는 iris 데이터를 random forest 로 분류한 예시이다.

In [ ]:
# 1. 필요 패키지 임포트
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# 2. 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

# 3. 데이터 살펴보기
print(df.info())

# 4. 데이터 전처리
df['species'].replace({"setosa" : 0, "versicolor" : 1, "virginica" : 2}, inplace = True)

# 5. 분석 데이터셋 준비
X = df[["sepal_length", "sepal_width", "petal_length", "petal_width"]]
y = df["species"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=11)

# 6.데이터분석 수행
dt = DecisionTreeClassifier(random_state = 11)

dt.fit(X_train, y_train)

pred = dt.predict(X_test)

#7. 성능평가 및 시각화
#Accuracy (TP+TN / TP+FP+TN+FN)
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,pred)
print(acc)

#오차행렬
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

#오차행렬에 기반한 모델 평가지표
from sklearn.metrics import classification_report
rpt = classification_report(y_test,pred)
print(rpt)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
0.9333333333333333
[[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.83      1.00      0.91        10
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



### 지도학습 - 분류  
지도학습은 정답이 있는 데이터가 주어진 상태에서 학습하는 방법이다. 크게 분류와 회귀(예측)로 구분할 수 있다.  
분류란 기존에 존재하는 데이터들간의 분류 카테고리를 학습, 파악하고 새로운 데이터에 대한 분류 카테고리를 판별하는 과정이다.  
분류는 학습 데이터를 기반으로 분류모델을 생성하고, 생성된 모델이 새로운 데이터 값이 주어졌을 때 결정값을 판별한다.  
* 이진분류 :  주어진 데이터에 대해 두 가지 중 하나로 분류하는것.  
* 다중분류 :  주어진 데이터에 대해 여러 가지 중 하나로 분류하는 것.  
  
다음과 같은 알고리즘들이 있다 -> 의사결정나무(Decision Tree), KNN(K-Nearest Neighbor), 로지스틱 회귀(Logistic Regression), 랜덤 포레스트(Random Forest),
나이브 베이즈(Naive Bayes), 신경망(Neural Network), 서포트벡터머신(SVM, Support Vector Machine)  


------
#### 의사결정나무

##### 알고리즘 개요  
* 의사결정을 위한 규칙을 나무 모양으로 조합하여 목표변수에 대한 분류를 수행하는 기법이다.  
* 목표변수가 이산형인 경우로 의사결정나무를 학습하는 것은 최종적으로 분류나무를 구축하는 과정이다.
* 의사결정나무 기법을 사용한 분석은 시장조사, 광고조사, 품질관리 등 다양한 분야에서 활용되고 있으며, 타겟 고객 분류, 고객 신용 분류, 행동 예측 등에 사용된다.  

##### 알고리즘 특징  
* 수학적 지식이 없어도 결과를 해석하고 이해하기 쉽다.  
* 수치 데이터 및 범주 데이터에 모두 사용 가능하다.
* 과대 적합의 위험이 높기 때문에, 학습모델이 과대적합 되지 않도록 적절히 조절되어야 한다.  

> 랜덤포레스트
> 부트스트래핑 기반 샘플링을 활용한 의사결정나무 생성 이후 배깅 기반 나무들을 모아 앙상블 학습하여 숲을 형성하게 되면 이를 랜덤포레스트라고 한다.



In [ ]:
# 의사결정나무를 이용한 타이타닉 데이터셋에서 탑습자들의 여러 속성데이터를 기반으로 생존여부를 예측한다.
'''
 접근방법
타이타닉 데이터셋은 여러 칼럼으로 구성되어 있으며, 이를 기반으로 Survived 칼럼의 값을 예측한다.
불필요한 속성은 제거하고 전처리과정을 거친 후, 사이킷런의 의사결정나무 알고리즘을 이용하여 학습 모델을 구축한 후 예측을 수행한다.
'''
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.describe()

d_mean = np.mean(df["Age"])
df["Age"].fillna(d_mean,inplace=True)
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

from sklearn.preprocessing import LabelEncoder
df["Sex"] = LabelEncoder().fit_transform(df["Sex"])
df["Embarked"] = LabelEncoder().fit_transform(df["Embarked"])
df["FamilySize"] = df["SibSp"] + df["Parch"]

X = df[["Pclass", "Sex", "Age", "Fare","Embarked","FamilySize"]]
y = df["Survived"]

train_x,test_x,train_y,test_y = train_test_split(X,y,test_size=0.2,random_state=11)

model = DecisionTreeClassifier(random_state=11)
model.fit(train_x,train_y)
pred = model.predict(test_x)
from sklearn.metrics import accuracy_score
acc = accuracy_score(test_y,pred)

cnt = 0
for i,j in enumerate(pred):
  if j == test_y.iloc[i]:
    cnt += 1
print(acc,(cnt/test_x.shape[0]))


0.7877094972067039 0.7877094972067039


#### KNN 알고리즘  
##### 알고리즘 개요  
* KNN 알고리즘은 지도학습의 한 종류로, 정답이 있는 데이터를 사용하여 분류 작업을 한다.
* 서로 가가운 점은 유사하다는 가정하에, 데이터로부터 거리가 가까운 K개의 다른 데이터의 정답을 참조하여 분류한다.  
> KNN알고리즘은 변수별 단위가 무엇이냐에 따라 거리가 달라지고 분류 결과가 달라질 수 있다.
따라서 KNN 알고리즘을 적용할때는 사전에 데이터를 표준화 해야한다.

##### 알고리즘 특징  
* 동작원리가 단순하여 이해하기 쉬우며, 알고리즘이 간단하여 구현하기 쉽다.
* 거리 기반의 연산으로, 숫자로 구분된 속성에 우수한 성능을 보인다.  
* 하나의 데이터를 예측할 때마다 전체 데이터와의 거리를 계산하기 때문에 차원(벡터)의 크기가 크면 계산량이 많아진다.  

In [4]:
# iris 데이터셋을 이용하여 꽃잎의 길이와 너비, 꽃받침의 길이와 너비를 가지고 붓꽃의 품종을 분류하는 문제를 KNN알고리즘을 사용해서 해결한다.
# KNN 알고리즘은 K값에 따라서 분류의 정확도가 달라지므로, 적절한 K값을 찾는것이 매우 중요하다.
# ex) k = 3이면 새로운 데이터로부터 가장 가까운 이웃 3개를 찾고, 그 중에서 가장 개수가 많은 값으로 분류한다.

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df["sepal_length"] = scaler.fit_transform(df[["sepal_length"]])
df["sepal_width"] = scaler.fit_transform(df[["sepal_width"]])
df["petal_length"] = scaler.fit_transform(df[["petal_length"]])
df["petal_width"] = scaler.fit_transform(df[["petal_width"]])

X = df[["sepal_length","sepal_width","petal_length","petal_width"]]
y = df["species"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=11)
print(X_train.shape, y_train.shape)

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)

from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, pred)
print(acc)

(120, 4) (120,)
0.9333333333333333


#### SVM(Support Vector Machine) 알고리즘
##### 알고리즘 개요  
* 서포트벡터머신은 기계학습의 분야 중 하나로 패턴 인식, 자료 분석을 위한 지도학습 모델이며, 주로 분류와 회귀 분석을 위해 사용한다.
* 두 카테고리 중 어느 하나에 속한 데이터가 어느 카테고리에 속할지 판단하는 비확률적 이진 선형 분류 모델을 만든다.
* 만들어진 분류 모델은 데이터가 사상된 공간에서 경계로 표현되는데 SVM알고리즘은 그 중 가장 큰 폭을 가진 경계를 찾는 알고리즘 이다.  
##### 알고리즘 특징
* 커널 트릭을 사용함으로써 다양한 데이터의 특성에 맞는 분류를 수행할 수 있다.
* 비교적 적은 학습데이터로도 정확도가 높은 분류를 기대할 수 있다. (전처리 과정을 통해 데이터의 특성을 잘 표현해야한다)  
* 변수가 많은경우 결정 경계 및 데이터의 시각화가 어려워 분류 결과의 이해가 어렵다.

In [35]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
d_mean = np.mean(df["Age"])
df["Age"].fillna(d_mean, inplace=True)
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace =True)
df.drop("Cabin", axis = 1, inplace =True)
df["FamilySize"] = df["SibSp"] + df["Parch"]

onehot_Sex = pd.get_dummies(df["Sex"])
onehot_Embarked = pd.get_dummies(df["Embarked"])

df = pd.concat([df,onehot_Sex,onehot_Embarked], axis = 1)
df.drop("Sex", axis = 1, inplace = True)
df.drop("Embarked", axis = 1, inplace = True)

X = df[["Pclass", "Age", "Fare", "FamilySize","female","male","C","Q","S"]]
y = df["Survived"]

svc = SVC(kernel='rbf')
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state =10
                                                    )

print(x_train.shape, y_train.shape)

svc.fit(x_train, y_train)
pred = svc.predict(x_test)

from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)
print("정확도 " , acc)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

mat = confusion_matrix(y_test,pred)
print(mat)

rep = classification_report(y_test,pred)
print(rep)

(623, 9) (623,)
정확도  0.7238805970149254
[[167   7]
 [ 67  27]]
              precision    recall  f1-score   support

           0       0.71      0.96      0.82       174
           1       0.79      0.29      0.42        94

    accuracy                           0.72       268
   macro avg       0.75      0.62      0.62       268
weighted avg       0.74      0.72      0.68       268

