# 2 유형 / 데이터 분석

------  
분석문제는 다음과 같은 순서를 따르자.
1. 필요 패키지 임포트  
2. 데이터 불러오기  
3. 데이터 살펴보기
4. 데이터 전처리
5. 분석 데이터셋 준비
6. 데이터 분석 수행
7. 성능평가 및 시각화
------  
아래는 iris 데이터를 random forest 로 분류한 예시이다.

In [21]:
# 1. 필요 패키지 임포트
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# 2. 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

# 3. 데이터 살펴보기
print(df.info())

# 4. 데이터 전처리
df['species'].replace({"setosa" : 0, "versicolor" : 1, "virginica" : 2}, inplace = True)

# 5. 분석 데이터셋 준비
X = df[["sepal_length", "sepal_width", "petal_length", "petal_width"]]
y = df["species"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=11)

# 6.데이터분석 수행
dt = DecisionTreeClassifier(random_state = 11)

dt.fit(X_train, y_train)

pred = dt.predict(X_test)

#7. 성능평가 및 시각화
#Accuracy (TP+TN / TP+FP+TN+FN)
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,pred)
print(acc)

#오차행렬
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

#오차행렬에 기반한 모델 평가지표
from sklearn.metrics import classification_report
rpt = classification_report(y_test,pred)
print(rpt)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
0.9333333333333333
[[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.83      1.00      0.91        10
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



### 지도학습 - 분류